"""create new tables

Revision ID: 2f8ba7dc3aa0
Revises: 955dc4504cc6
Create Date: 2021-12-02 12:09:08.425557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8ba7dc3aa0'
down_revision = '955dc4504cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_box',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cash', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('card', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_box_user_id'), 'cash_box', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('firm_flag', sa.Boolean(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_firm_id'), 'expenses', ['firm_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_firm_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_cash_box_user_id'), table_name='cash_box')
    op.drop_table('cash_box')
    # ### end Alembic commands ###
