"""Initial migrate

Revision ID: 320b061e6aa7
Revises: 
Create Date: 2021-11-27 12:59:00.277742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320b061e6aa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('paid_for', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('debt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('firms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('paid_for', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('debt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_uri', sa.String(), nullable=False),
    sa.Column('paid_for', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('payment', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('previous_debt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('debt', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('firms')
    op.drop_table('debtors')
    # ### end Alembic commands ###
