"""deleete foreignkey for user table in invoice tables

Revision ID: 366a528925af
Revises: a036d8864675
Create Date: 2021-11-30 08:27:50.992761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366a528925af'
down_revision = 'a036d8864675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_user_id', table_name='invoices')
    op.drop_constraint('invoices_user_id_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('invoices_user_id_fkey', 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_invoices_user_id', 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###
