"""ada

Revision ID: 3e963e848711
Revises: e99392e1d0cf
Create Date: 2021-12-01 09:13:09.178626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e963e848711'
down_revision = 'e99392e1d0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_firm_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'firms', ['firm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_firm_id_fkey', 'invoices', 'firms', ['firm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
