"""initial migrate

Revision ID: 451093000213
Revises: 
Create Date: 2022-01-10 10:00:10.511035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451093000213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chief', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chief')
    # ### end Alembic commands ###
