"""added relationsship and foreignKeys

Revision ID: 4e7b7f8ba1c6
Revises: 5f796bf72304
Create Date: 2021-11-28 08:43:38.284819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7b7f8ba1c6'
down_revision = '5f796bf72304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_debtors_user_id'), 'debtors', ['user_id'], unique=False)
    op.create_foreign_key(None, 'debtors', 'users', ['user_id'], ['id'])
    op.add_column('firms', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_firms_user_id'), 'firms', ['user_id'], unique=False)
    op.create_foreign_key(None, 'firms', 'users', ['user_id'], ['id'])
    op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_firm_id'), 'invoices', ['firm_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_firm_id'), table_name='invoices')
    op.drop_column('invoices', 'user_id')
    op.drop_constraint(None, 'firms', type_='foreignkey')
    op.drop_index(op.f('ix_firms_user_id'), table_name='firms')
    op.drop_column('firms', 'user_id')
    op.drop_constraint(None, 'debtors', type_='foreignkey')
    op.drop_index(op.f('ix_debtors_user_id'), table_name='debtors')
    op.drop_column('debtors', 'user_id')
    # ### end Alembic commands ###
