"""create finances table for firm table

Revision ID: 75c59ca3ae76
Revises: 8f3b9686e8d5
Create Date: 2021-12-05 16:58:45.516723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c59ca3ae76'
down_revision = '8f3b9686e8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
