"""create finances table for firm table

Revision ID: 8f3b9686e8d5
Revises: bac795e75512
Create Date: 2021-12-05 16:40:54.276370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3b9686e8d5'
down_revision = 'bac795e75512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
