"""change relationships and foreignkeys

Revision ID: 955dc4504cc6
Revises: fd9439bf4c16
Create Date: 2021-12-01 09:30:09.185922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955dc4504cc6'
down_revision = 'fd9439bf4c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_firm_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'firms', ['firm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_firm_id_fkey', 'invoices', 'firms', ['firm_id'], ['id'])
    # ### end Alembic commands ###
