"""ada

Revision ID: 9bfff75f152e
Revises: e5ff26adeab6
Create Date: 2021-12-01 06:57:18.426338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfff75f152e'
down_revision = 'e5ff26adeab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_user_id', table_name='invoices')
    op.drop_constraint('invoices_user_id_fkey', 'invoices', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('invoices_user_id_fkey', 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_invoices_user_id', 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###
