"""empty message

Revision ID: a89236a0bc9c
Revises: 70d26d767908
Create Date: 2022-01-31 06:23:18.409625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89236a0bc9c'
down_revision = '70d26d767908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtors', sa.Column('paid', sa.Numeric(precision=10, scale=3), nullable=True))
    op.drop_column('debtors', 'paid_for')
    op.add_column('finances', sa.Column('paid', sa.Numeric(precision=10, scale=3), nullable=True))
    op.drop_column('finances', 'paid_for')
    op.add_column('invoices', sa.Column('to_pay', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('invoices', sa.Column('paid', sa.Numeric(precision=10, scale=3), nullable=True))
    op.drop_column('invoices', 'payment')
    op.drop_column('invoices', 'paid_for')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid_for', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payment', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'paid')
    op.drop_column('invoices', 'to_pay')
    op.add_column('finances', sa.Column('paid_for', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.drop_column('finances', 'paid')
    op.add_column('debtors', sa.Column('paid_for', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.drop_column('debtors', 'paid')
    # ### end Alembic commands ###
