"""create finances table for firm table

Revision ID: bac795e75512
Revises: db854c62992b
Create Date: 2021-12-05 16:32:54.298669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac795e75512'
down_revision = 'db854c62992b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
