"""change again foreignkey in invoice table

Revision ID: d5994d8dc0c1
Revises: 366a528925af
Create Date: 2021-11-30 08:32:15.023354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5994d8dc0c1'
down_revision = '366a528925af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###
