"""changed relationship in finances table

Revision ID: db854c62992b
Revises: b6d7ce0dd695
Create Date: 2021-12-05 16:20:34.459655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db854c62992b'
down_revision = 'b6d7ce0dd695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
