"""ada

Revision ID: e5ff26adeab6
Revises: f54c62078e65
Create Date: 2021-12-01 06:49:34.916272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ff26adeab6'
down_revision = 'f54c62078e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
