"""ada

Revision ID: e99392e1d0cf
Revises: 9bfff75f152e
Create Date: 2021-12-01 08:38:19.558721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99392e1d0cf'
down_revision = '9bfff75f152e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
